version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/uat

permissions:
   - object: /var/www/html/uat
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - file

hooks: 

  BeforeInstall:
    - location: scripts/stop_server.sh
      runas: root
      timeout: 300

    - location: scripts/clean_env_before_deploy.sh
      runas: root
      timeout: 300

  AfterInstall:
    - location: scripts/clean_www_after_deploy.sh
      runas: root
      timeout: 300

    - location: scripts/start_server.sh
      runas: root
      timeout: 300

